labs/Lab5/CharacterRoster.Web/Models/CharacterModel.cs
/*
 * ITSE 1430
 * Donald Helaire
 * Lab5
 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace CharacterRoster.Web.Models
{
    public class CharacterModel
    {
        public CharacterModel ()
        {
        }

        public CharacterModel ( object character )
        {
        }

        public int Id { get; set; }

        [Required(AllowEmptyStrings = false)]
        public string CharacterName { get; set; }
        public string CharacterRoster { get; set; }
        public string Profession { get; set; }
        public string Race { get; set; }
        public int Attributes { get; set; }
        public string Description { get; set; }

        internal object ToCharacter ()
        {
            throw new NotImplementedException();
        }

        internal object ToMovie ()
        {
            throw new NotImplementedException();
        }
    }
}

labs/Lab5/CharacterRoster.Web/Controllers/CharacterController.cs
/*
 * ITSE 1430
 * Donald Helaire
 * Lab5
 */

using System;
using System.Configuration;
using System.Web.Mvc;
using CharacterCreator;
using CharacterCreator.Memory;
using CharacterRoster.Web.Models;

namespace CharacterCreator.Memory 
{ 
}
namespace CharacterRoster.Web.Controllers
{
    public class CharacterController : Controller
    {
        private object id;

        public CharacterController ()
        {
            var connString = ConfigurationManager.ConnectionStrings["CharacterDatabase"].ConnectionString;

            var _database = new MemoryCharacterDatabase(connString);
        }
        public ActionResult Index()
        {
            var character = _database.GetAll();

            //var model = character.Select(x => new CharacterModel(x));
            var model = character;

            return View("List", model);
        }
        public ActionResult Details (int id)
        {
            var character = _database.Get(id);
            if (character == null)
                return HttpNotFound();

            return View(new CharacterModel(character));
        }

        public ActionResult Edit ( int id )
        {
            var character = _database.Get(id);
            if (character == null)
                return HttpNotFound();

            return View(new CharacterModel(character));
        }

        [HttpPost]
        public ActionResult Edit ( CharacterModel model )
        {
            if (ModelState.IsValid)
            {
                _database.Update(model.Id, model.ToCharacter());
            };

            return View(model);
        }
        public ActionResult Create () => View(new CharacterModel());

        [HttpPost]
        public ActionResult Create ( CharacterModel model )
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var character = _database.Add(model.ToCharacter());

                    return RedirectToAction(nameof(Details), new { id = model.Id });
                } catch (Exception e)
                {
                    ModelState.AddModelError("", e.Message);
                };
            };

            return View(model);
        }

        public ActionResult Delete ( int id )
        {
            var character = _database.Get(id);
            if (character == null)
                return HttpNotFound();

            return View(new CharacterModel(character));
        }

        [HttpPost]
        public ActionResult Delete ( CharacterModel character )
        {
            try
            {
                _database.Delete(character.Id);

                return RedirectToAction(nameof(Index));
            } catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
            };

            return View(character);
        }

    }
    internal class _database
    {
        internal static object Add ( object v )
        {
            throw new NotImplementedException();
        }

        internal static void Delete ( int id )
        {
            throw new NotImplementedException();
        }

        internal static object Get ( object id )
        {
            throw new NotImplementedException();
        }

        internal static object GetAll ()
        {
            throw new NotImplementedException();
        }

        internal static void Update ( int id, object p )
        {
            throw new NotImplementedException();
        }
    }
}

labs/Lab5/CharacterRoster.Web/Controllers/HomeController.cs
/*
 * ITSE 1430
 * Donald Helaire
 * Lab5
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CharacterRoster.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About() => View();
        //public ActionResult Contact()
        //{
        //    ViewBag.Message = "Your contact page.";

            //return View();
        //}
    }
}

labs/Lab5/CharacterRoster.Web/Views/Character/Create.cshtml
@model CharacterRoster.Web.Models.CharacterModel

@{
    ViewBag.Title = "Add New";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CharacterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profession, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profession, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profession, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Race, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Race, new { htmlAttributes = new { @class = "form-control", style = "width: 80px;" } })
                @Html.ValidationMessageFor(model => model.Race, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Attributes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Attributes, new { htmlAttributes = new { @class = "form-control", style = "width: 80px;" } })
                @Html.ValidationMessageFor(model => model.Attributes, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

labs/Lab5/CharacterRoster.Web/Views/Character/Delete.cshtml
@model CharacterRoster.Web.Models.CharacterModel

@{
    ViewBag.Title = "Delete";
}

<h2>@ViewBag.Title</h2>

<p>
    Are you sure you want to delete '@model.CharacterName'?
</p>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CharacterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Race)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Race)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Profession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Attributes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Attributes)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

labs/Lab5/CharacterRoster.Web/Views/Character/Details.cshtml
@model CharacterRoster.Web.Models.CharacterModel

@{
    ViewBag.Title = Model.CharacterName;
}

<h2>@ViewBag.Title</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CharacterName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CharacterName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Race)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Race)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Profession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Attributes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Attributes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

labs/Lab5/CharacterRoster.Web/Views/Character/Edit.cshtml
@model CharacterRoster.Web.Models.CharacterModel

@{
    ViewBag.Title = Model.CharacterName + " (Edit)";
}

<h2>Edit @Model.CharacterName</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CharacterName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CharacterName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CharacterName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Race, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Race, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Race, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profession, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profession, new { htmlAttributes = new { @class = "form-control", style = "width: 80px;" } })
                @Html.ValidationMessageFor(model => model.Profession, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Attributes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Attributes, new { htmlAttributes = new { @class = "form-control", style = "width: 80px;" } })
                @Html.ValidationMessageFor(model => model.Attributes, "", new { @class = "text-danger" })
            </div>
        </div>


    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

labs/Lab5/CharacterRoster.Web/Views/Character/Index.cshtml
@model IEnumerable<CharacterRoster.Web.Models.CharacterModel>

@{
    ViewBag.Title = "Characters";
}

<h2>Characters</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CharacterName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CharacterRoster)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profession)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Race)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Attributes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CharacterName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CharacterRoster)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Profession)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Race)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Attributes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

labs/Lab5/CharacterRoster.Web/Views/Character/List.cshtml
@model IEnumerable<CharacterRoster.Web.Models.CharacterModel>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CharacterName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CharacterRoster)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profession)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Race)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Attributes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CharacterName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CharacterRoster)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Profession)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Race)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Attributes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

labs/Lab5/CharacterRoster.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>

<p>
    Donald Helaire <br />
    ITSE 1430
</p>

labs/Lab5/CharacterRoster.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<Course>
    ITSE 1430<br />
    Fall 2020<br />
    Donald Helaire<br />
</Course>

labs/Lab5/CharacterRoster.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Character Roster</h2>

labs/Lab5/CharacterRoster.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Character Roster - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizer")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Characters", "Index", "Character")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Character Roster</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>